spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  # ================= 数据库连接配置 =================
  datasource:
    url: jdbc:mysql://localhost:3306/cms_database
    username: root
    password: 409852
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ================= JPA 配置 =================
  jpa:
    show-sql: true          # 开发环境显示 SQL
    hibernate:
      ddl-auto: create      # 自动更新表结构（生产环境建议改为 none）
    properties:
      hibernate:
        format_sql: true    # 格式化 SQL 输出
        use_sql_comments: true # 显示 SQL 注释
        jdbc:
          lob:
            non_contextual_creation: true  # 避免 LOB 警告

  # ================= Redis配置 =================
  data:
    redis:
      host: 0.0.0.0
      port: 6379
      password:

# ================= 服务器配置 =================
server:
  address: 0.0.0.0
  port: 8080

# ================= 日志配置 =================
logging:
  file:
    name: logs/app.log    # 指定日志文件名（优先使用name，与path二选一）
    # path: /var/logs/    # 或指定目录（生成的文件名为spring.log）
  level:
    root: info            # 全局日志级别
    com.example: debug    # 指定包的日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"